name: prometheus
title: Prometheus
icon: prometheus
type: service
scalable: false
labels:
- prometheus
- metrics
options:
- version: '3.13'
  tag: '3.13'
  default: true

  eol: '2027-07-31T00:00:00+00:00'
endpoints:
- name: prometheus
  ports:
  - name: prometheus
    number: 9090
    type: http
    main: true

volumes:
- name: data
  title: Data
  size: 10
  helm:
    labels: persistence.labels
    values:
    - name: persistence.enabled
      value: true
    - name: persistence.size
      value: '{{volumes.data.size}}Gi'
    - name: persistence.existingClaim
      value: '{{volumes.data.claim}}'

configs:
- name: config
  title: Prometheus config
  helm: config.prometheusYml
  processTokens: true
  config: prometheus.yml.tmpl

helm:
  name: wodby
  source: oci://registry-1.docker.io/wodby/prometheus
  chart: oci://registry-1.docker.io/wodby/prometheus
  version: 0.1.0

workloads:
- name: main
  selector:
    matchLabels:
      app.kubernetes.io/instance: '{{helm.release}}'
  kind: statefulset
  primary: true
  helm:
    labels: podLabels
    annotations: podAnnotations
    volumes: extraVolumes
  containers:
  - name: prometheus
    image: wodby/prometheus
    helm:
      resources: resources
      env: envVars
      mounts: extraVolumeMounts
