name: prometheus
title: Prometheus
type: infrastructure
hostname: prometheus
containers:
- name: prometheus
  ports:
  - name: prometheus
    number: 9090
    type: http
    main: true

helm:
  name: prometheus-community
  source: https://prometheus-community.github.io/helm-charts
  chart: prometheus-community/prometheus
  version: 25.19.1
  configurations:
  - name: prometheus
    annotations: server.deploymentAnnotations
    labels: server.labels
    resources: server.resources
    env: server.env
    ingresses: 
    - name: prometheus
      service: '{{service.name}}'    
  values:
  - name: prometheus-pushgateway.enabled
    value: false
  - name: alertmanager.enabled
    value: false
  - name: kube-state-metrics.enabled
    value: false
  - name: prometheus-node-exporter.enabled
    value: false
  - name: scrapeConfigFiles
    value: |
      - job_name: kube-state-metrics
        honor_timestamps: true
        scrape_interval: 1m
        scrape_timeout: 1m
        metrics_path: /metrics
        scheme: http
        static_configs:
        - targets:
          - kube-state-metrics:8080

      - job_name: metrics-server
        honor_timestamps: true
        scrape_interval: 1m
        scrape_timeout: 1m
        scheme: https
        static_configs:
        - targets:
          - metrics-server:443

      - job_name: node-exporter
        honor_timestamps: true
        scrape_interval: 1m
        scrape_timeout: 1m
        scheme: http
        static_configs:
        - targets:
          - node-exporter:9100

